### PR TITLE
added placeholders for run(action = <action>, params = <action-params>) in line 67

### PR DESCRIPTION
**Pull request by szandany**
added placeholders for 'run(action = '<action>', params = '<action-params>')' in line 67" in the index.js file.

### CODE REVIEW

**Comment by alan-czajkowski** [comment]
is this project in active development? would be nice to have :)

**Comment by tabuckner** [comment]
@alan-czajkowski definitely! what's your use case?

**Comment by alan-czajkowski** [comment]
@tabuckner currently using Liquibase with Java Spring Boot apps, and would like to continue using the framework for NodeJS apps (talking to Oracle)

**Comment by jgtvares** [comment]
Quick question: why is this lib using Liquibase 4.0 beta1 version? Is there any intention to upgrade?
I'm experiencing this [issue](https://github.com/liquibase/liquibase/issues/1510). 
And it seems to have been fixed already in newer versions!

**Comment by tabuckner** [comment]
@alan-czajkowski @jgtvares Hey guys, recently re-released this library after some refactoring and wanted to let you guys know I took your comments into consideration:

- @alan-czajkowski The new release has a substantially different API than the previous release which relied heavily on an understanding of how Liquibase works. I would love if you could take a look at the [new setup here](https://www.npmjs.com/package/liquibase). Now it has support for TypeScript, a proxied API that brings Liquibase core into the Node world in a familiar fashion.

- @jgtvares I've also just released a zero-dependency version of the library under the `npm tag` `@pd` for Peer Dependency. This will allow you to use any version of Liquibase you like with a couple minor changes to the configuration of `node-liquibase`. If you're still interested in using what I've dubbed a 'Bundled Version' of this library, you can find [NPM releases here](https://www.npmjs.com/package/liquibase) and some information about how to select the correct version of `node-liquibase` [here](https://www.npmjs.com/package/liquibase#bundled-version-numbers). I'll provide a short description below of how it works.

*Deciding Which Version of node-liquibase to Use*
The major and minor version numbers of `node-liquibase` will align with a corresponding [Liquibase Core](https://github.com/liquibase/liquibase) release.

For Example:
> "I want to use Liquibase v4.3.3 in a Node application."

```bash
yarn add liquibase@4.3
```

This should (I think, anyways 😂 ) install the latest `patch` version of `node-liquibase` 4.3.x, which will contain a 'bundled'  Liquibase Core at v4.3.3. It is safe to assume that the `patch` number of `node-liquibase` will not reliably align with Liquibase Core.

**Comment by tabuckner** [comment]
Closing this PR as previous library has been deprecated.

**Comment by alan-czajkowski** [comment]
@tabuckner thank you for your efforts!

**Comment by jgtvares** [comment]
@tabuckner Thank you for taking our issues into account! :pray:

**Pull request closed without merging**
