### PR TITLE
Feature/substitution params taylor

### PR DESCRIPTION
**Pull request by tabuckner**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by mariochampion** [comment]
yo @tabuckner !! thanks for the PR

**Comment by filipelautert** [comment]
Hey @tabuckner - everything is failing with error `The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1" `. 
Maybe we should drop node 10.x and 12.x test support [here](https://github.com/liquibase/node-liquibase/blob/master/.github/workflows/node.js.yml) as they are not supported anymore as per https://nodejs.dev/en/about/releases/ ?

**Comment by filipelautert** [comment]
Hello @ijakab - could you give a try to this pr as a replacement for yours PR https://github.com/liquibase/node-liquibase/pull/45 ?

**Review by filipelautert — APPROVED** [review]

**Comment by filipelautert** [comment]
@MalloD12 can you approve this one? seems as I fixed conflicts I need another reviewer before merging.

**Review by MalloD12 — APPROVED** [review]

**Pull request merged**
